
version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/dockerfile
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ./output:/app/output
    environment:
      - OUTPUT_DIR=/app/output
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  frontend:
    build:
      context: frontend
      dockerfile: dockerfile
    ports:
      - "${FRONTEND_PORT:-8501}:8501"
    volumes:
      - ./frontend:/app
      - ./output:/app/output
    environment:
      - OUTPUT_DIR=/app/output
      - BACKEND_URL=http://backend:8000
    env_file:
      - .env
    depends_on:
      - backend
