[project]
name = "step1x3d-backend"
version = "1.0.0"
dependencies = [
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.32.0",
    "python-multipart>=0.0.12",
    "python-dotenv>=1.0.0",
    "pillow>=10.0.0",
    "requests>=2.32.0",
]

